# -*- coding: utf-8 -*-
"""Python program

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KqhPVL4Ofjv3JTmgAob019isdtvQIeYn

**Variables**
"""

name="hello"
print(name)

num=9
y="john"
print(num)
print(y)

name_1="hey"
print(name_1)

simple_man="Myself"
print(simple_man)

"""**String**"""

name='Simran jeet'
print(name.title())
#title() used to caps first letter of each word in string

first_name="Simranjeet"
last_name='kaur'
print(first_name +' '+ last_name.title())
#this is concatination

name='simran'
name1='\tjeet'
print(name.upper())
print(name.upper()+ name1.title().upper())
#\t is used to give space,it is a tab
#upper() and lower() are used to change case of text

myfavlang='Languages:  \n\tPython\n\tJava\n\tC'
print(myfavlang)
#\n is used for new line

# fav_lang=' Python '
# fav_lang.rstrip().lstrip()
fav_lang1=' Python  '
fav_lang1.strip()
#here we. directly call funtion withoutusing print
#rstrip() is used to remove whte space from right side of the string
#lstrip() is used to remove white space from leftside of the string
#strip() is used to remove space from both side

"""**Python as a number**"""

2+2*(6*2)
#in python we can directly use calculations